typography_spectrum: 0.743
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9043516574893147
  lightness: 0.25604801531881094
  saturation: 0.9163996856659651
  rhythmicContrast: 0.3955006957985461
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.207
analytics:
  google: null
  facebook: null
  twitter: null
name: leonardodioko
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: How much tourism is too much?
description: Destination carrying capacity in the age of mass travel
purpose: []
